[2022-10-02 00:18:21,118] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-01T23:05:00+00:00 [queued]>
[2022-10-02 00:18:21,178] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-01T23:05:00+00:00 [queued]>
[2022-10-02 00:18:21,184] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-02 00:18:21,186] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-10-02 00:18:21,189] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-02 00:18:21,249] {taskinstance.py:1259} INFO - Executing <Task(DockerOperator): docker_command_sleep> on 2022-10-01 23:05:00+00:00
[2022-10-02 00:18:21,259] {standard_task_runner.py:52} INFO - Started process 706 to run task
[2022-10-02 00:18:21,288] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'docker_operator_demo', 'docker_command_sleep', 'scheduled__2022-10-01T23:05:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmp4jccq04g', '--error-file', '/tmp/tmprps7j8tv']
[2022-10-02 00:18:21,291] {standard_task_runner.py:77} INFO - Job 10: Subtask docker_command_sleep
[2022-10-02 00:18:21,506] {logging_mixin.py:109} INFO - Running <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-01T23:05:00+00:00 [running]> on host 336e822c453c
[2022-10-02 00:18:21,763] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=docker_operator_demo
AIRFLOW_CTX_TASK_ID=docker_command_sleep
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T23:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-01T23:05:00+00:00
[2022-10-02 00:18:21,862] {docker.py:258} INFO - Starting docker container from image alpine:latest
[2022-10-02 00:18:21,911] {docker.py:269} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2022-10-02 00:18:22,349] {docker.py:320} INFO - hello
[2022-10-02 00:18:22,591] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=docker_operator_demo, task_id=docker_command_sleep, execution_date=20221001T230500, start_date=20221002T001821, end_date=20221002T001822
[2022-10-02 00:18:23,006] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-10-02 00:18:23,205] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
