[2022-10-02 05:09:17,677] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-02T03:05:00+00:00 [queued]>
[2022-10-02 05:09:17,775] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-02T03:05:00+00:00 [queued]>
[2022-10-02 05:09:17,778] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-02 05:09:17,780] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-10-02 05:09:17,782] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-02 05:09:17,857] {taskinstance.py:1259} INFO - Executing <Task(DockerOperator): docker_command_sleep> on 2022-10-02 03:05:00+00:00
[2022-10-02 05:09:17,868] {standard_task_runner.py:52} INFO - Started process 941 to run task
[2022-10-02 05:09:17,888] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'docker_operator_demo', 'docker_command_sleep', 'scheduled__2022-10-02T03:05:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmpwg4lwr9g', '--error-file', '/tmp/tmpm_o2qlto']
[2022-10-02 05:09:17,892] {standard_task_runner.py:77} INFO - Job 23: Subtask docker_command_sleep
[2022-10-02 05:09:18,179] {logging_mixin.py:109} INFO - Running <TaskInstance: docker_operator_demo.docker_command_sleep scheduled__2022-10-02T03:05:00+00:00 [running]> on host 336e822c453c
[2022-10-02 05:09:18,676] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=docker_operator_demo
AIRFLOW_CTX_TASK_ID=docker_command_sleep
AIRFLOW_CTX_EXECUTION_DATE=2022-10-02T03:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-02T03:05:00+00:00
[2022-10-02 05:09:18,905] {docker.py:258} INFO - Starting docker container from image alpine:latest
[2022-10-02 05:09:18,995] {docker.py:269} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2022-10-02 05:09:20,745] {docker.py:320} INFO - hello
[2022-10-02 05:09:21,429] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=docker_operator_demo, task_id=docker_command_sleep, execution_date=20221002T030500, start_date=20221002T050917, end_date=20221002T050921
[2022-10-02 05:09:21,591] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-10-02 05:09:21,814] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
